name: Test
"on":
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    uses: oscard0m/.github/.github-octokit/workflows/test.yml@add-shared-action
    with:
      node_versions: '[14,16,18]'
